apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: enterprise-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: enterprise-backend:latest
          ports:
            - containerPort: 5000

          envFrom:
            - configMapRef:
                name: enterprise-config

          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: enterprise-secret
                  key: JWT_SECRET
